#!/bin/sh

bash $HOME/.config/scripts/autorun.sh

# set mouse pointer
xsetroot -cursor_name left_ptr

# Define window size of floating windows
width=1600
height=900

# Calculate the position to center the window
# Get the current screen resolution
resolution=$(xrandr | awk '/\*/ {print $1; exit}')

# Extract width and height from the resolution
resolution_width=$(echo "$resolution" | cut -d 'x' -f 1)
resolution_height=$(echo "$resolution" | cut -d 'x' -f 2)
x_pos=$(((resolution_width - width) / 2))
y_pos=$(((resolution_height - height) / 2))

if [[ $HOSTNAME == olymp ]]; then
	bspc wm -O DisplayPort-0 DisplayPort-1
	bspc monitor DisplayPort-0 -d I II III IV
	bspc monitor DisplayPort-1 -d V VI VII
else
	bspc monitor primary -d I II III IV V VI VII
fi

# load pywal colors
# . "${HOME}/.cache/wal/colors.sh"

bspc config border_width 5
bspc config focused_border_color "#FFFFFF"
bspc config normal_border_color "#1a1b26"

bspc config window_gap 5
bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true

# Application Rules

bspc rule -a firefox desktop='^5' follow=off
bspc rule -a Google-chrome desktop='^5' follow=off
bspc rule -a Thorium-browser desktop='^5' follow=off
bspc rule -a Spotify desktop='^6' follow=off
bspc rule -a kdenlive desktop='^2' follow=off
bspc rule -a feh state=floating rectangle=$width"x"$height"+"$x_pos"+"$y_pos
bspc rule -a Bitwarden state=floating
# bspc rule -a steam state=floating

# bspc rule -a Gimp desktop='^4' state=floating follow=on
# bspc rule -a firefox desktop='^5'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
#bspc rule -a TelegramDesktop state=floating follow=off
#bspc rule -a Firefox state=floating rectangle=1600x900+160+90 desktop='^1'
#bspc rule -a Lutris state=floating follow=off rectangle=1200x700+360+190 desktop='^6'
#bspc rule -a mpv state=floating rectangle=800x450+560+315 follow=off
#bspc rule -a dmenu rectangle=900x22+610+90
#bspc rule -a Media viewer rectangle=1350x900+285+90 state=floating
#bspc rule -a Inkscape desktop='^3'
#bspc rule -a Blender desktop='^2'
